//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeitiesClothings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeitiesClothings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annotation_2020_09_06_172921 {
            get {
                object obj = ResourceManager.GetObject("Annotation 2020-09-06 172921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annotation_2020_09_06_172921__2_ {
            get {
                object obj = ResourceManager.GetObject("Annotation 2020-09-06 172921 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap automn_peonies {
            get {
                object obj = ResourceManager.GetObject("automn peonies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_panther {
            get {
                object obj = ResourceManager.GetObject("black panther", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDTS08LK {
            get {
                object obj = ResourceManager.GetObject("DDTS08LK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDTS08RS_Red_Sun_Glasses {
            get {
                object obj = ResourceManager.GetObject("DDTS08RS-Red-Sun-Glasses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMD_BLACK_WHITE_CHAIN_TRACKSUIT {
            get {
                object obj = ResourceManager.GetObject("DMD-BLACK-WHITE-CHAIN-TRACKSUIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMD_BUNNY_JACKET_DMDJ003NRN {
            get {
                object obj = ResourceManager.GetObject("DMD-BUNNY-JACKET-DMDJ003NRN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMD_GOLD_WHITE_STRIPES_TRACKSUIT {
            get {
                object obj = ResourceManager.GetObject("DMD-GOLD-WHITE-STRIPES-TRACKSUIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMDTS03BLC_BLACK_CHAIN_LACE {
            get {
                object obj = ResourceManager.GetObject("DMDTS03BLC-BLACK-CHAIN-LACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMDTS08NC_NAVY_TSHIRT_500x500 {
            get {
                object obj = ResourceManager.GetObject("DMDTS08NC-NAVY-TSHIRT-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DMDTS08WG_WHITE_GOLF_PRINT {
            get {
                object obj = ResourceManager.GetObject("DMDTS08WG-WHITE-GOLF-PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lime_rr_windbreaker {
            get {
                object obj = ResourceManager.GetObject("lime rr windbreaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MENS_SS_T_SHIRT_PRINTED_LEOPARD_BLACK {
            get {
                object obj = ResourceManager.GetObject("MENS-SS-T-SHIRT-PRINTED-LEOPARD-BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MENS_SS_T_SHIRT_PRINTED_NAVY_POCKET_SLEEVE_2 {
            get {
                object obj = ResourceManager.GetObject("MENS-SS-T-SHIRT-PRINTED-NAVY-POCKET-SLEEVE-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MENS_SS_T_SHIRT_PRINTED_POCKET_NAVY_ROSES {
            get {
                object obj = ResourceManager.GetObject("MENS-SS-T-SHIRT-PRINTED-POCKET-NAVY-ROSES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MENS_SS_T_SHIRT_PRINTED_RED_GOLFINO_3 {
            get {
                object obj = ResourceManager.GetObject("MENS-SS-T-SHIRT-PRINTED-RED-GOLFINO-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MENS_SS_T_SHIRT_PRINTED_RED_GOLFINO_31 {
            get {
                object obj = ResourceManager.GetObject("MENS-SS-T-SHIRT-PRINTED-RED-GOLFINO-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap northern_lights {
            get {
                object obj = ResourceManager.GetObject("northern lights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_roses {
            get {
                object obj = ResourceManager.GetObject("red roses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RM0041CBR_WINDBREAKER_2_1200x1200 {
            get {
                object obj = ResourceManager.GetObject("RM0041CBR_WINDBREAKER_2_1200x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RMS011CBP_WINDBREAKER_1_1200x1200 {
            get {
                object obj = ResourceManager.GetObject("RMS011CBP_WINDBREAKER_1_1200x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROSESWREATHCYCLINGTOP {
            get {
                object obj = ResourceManager.GetObject("ROSESWREATHCYCLINGTOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
